### ISSUE TITLE
Only partial rebranding with Sierra (beta 7)

### ISSUE THREAD

**Issue by miikkali** [ox-it/munki-rebrand#2] opened 2016-08-25 11:27 UTC
Hello! I'm testing munki_rebrand.py on macOS Sierra beta 7. 

Issue: after installing the rebranded munkitools.pkg and running MSC, the title and menu bars of MSC still read the standard “Managed Software Center” rather than “Our Rebranded Software Centre”.

The app icon and the name of the app do show our rebranding as expected, but the title and menu bars do not.

I installed the same pkg on a few machines running El Capitan 10.11.6, and the title and menu bars get the rebranding as expected, so I see this behaviour only with Sierra (beta 7). 

Same behaviour with munkitools 2.7.x and 2.8.x.

**Comment by miikkali** [comment] 2016-08-26 06:31
Here's the output of the script: 

```
mleppiha$ ./munki_rebrand.py 
Cleaning up previous runs
Password:
Cloning git repo
Cloning into 'munki'...
remote: Counting objects: 16071, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 16071 (delta 0), reused 0 (delta 0), pack-reused 16069
Receiving objects: 100% (16071/16071), 36.54 MiB | 5.32 MiB/s, done.
Resolving deltas: 100% (11563/11563), done.
Checking connectivity... done.
Replacing Managed Software Center with Rebranded MSC
Replace icons with Rebranded MSC.icns
Building Munki

            #####################################################
            ##  Please enter your sudo password when prompted  ##
            #####################################################

Build variables

  Bundle ID: com.googlecode.munki
  Munki root: /path/to/munki_rebrand/munki
  Output directory: /path/to/munki_rebrand
  munki core tools version: 2.8.1.2835
  LaunchAgents/LaunchDaemons version: 2.0.0.1969
  Apps package version: 4.2.2759

  metapackage version: 2.8.1.2835

Building Managed Software Update.xcodeproj...
2016-08-26 09:25:23.697 xcodebuild[6259:117215] Failed to locate a valid instance of CoreSimulatorService in the bootstrap.  Adding it now.
Managed Software Center.app version: 4.2.2759
Building MunkiStatus.xcodeproj...
MunkiStatus.app version: 4.0.2751

Creating core package template...
Creating admin package template...
Creating applications package template...
Creating launchd package template...
Creating metapackage template...
Setting ownership to root...

Packaging munkitools_core-2.8.1.2835.pkg
pkgbuild: Inferring bundle components from contents of /var/folders/0z/7chp1qyj2dxds3pkg_59q5kr0000gp/T/munkipkg.9aYo8w3N/munki_core
pkgbuild: Writing new component property list to /var/folders/0z/7chp1qyj2dxds3pkg_59q5kr0000gp/T/munkipkg.9aYo8w3N/munki_core_component.plist
pkgbuild: Reading components from /var/folders/0z/7chp1qyj2dxds3pkg_59q5kr0000gp/T/munkipkg.9aYo8w3N/munki_core_component.plist
pkgbuild: Wrote package to /var/folders/0z/7chp1qyj2dxds3pkg_59q5kr0000gp/T/munkipkg.9aYo8w3N/munki_mpkg/munkitools_core-2.8.1.2835.pkg

Packaging munkitools_admin-2.8.1.2835.pkg
pkgbuild: Inferring bundle components from contents of /var/folders/0z/7chp1qyj2dxds3pkg_59q5kr0000gp/T/munkipkg.9aYo8w3N/munki_admin
pkgbuild: Writing new component property list to /var/folders/0z/7chp1qyj2dxds3pkg_59q5kr0000gp/T/munkipkg.9aYo8w3N/munki_admin_component.plist
pkgbuild: Reading components from /var/folders/0z/7chp1qyj2dxds3pkg_59q5kr0000gp/T/munkipkg.9aYo8w3N/munki_admin_component.plist
pkgbuild: Wrote package to /var/folders/0z/7chp1qyj2dxds3pkg_59q5kr0000gp/T/munkipkg.9aYo8w3N/munki_mpkg/munkitools_admin-2.8.1.2835.pkg

Packaging munkitools_app-4.2.2759.pkg
pkgbuild: Inferring bundle components from contents of /var/folders/0z/7chp1qyj2dxds3pkg_59q5kr0000gp/T/munkipkg.9aYo8w3N/munki_app
pkgbuild: Writing new component property list to /var/folders/0z/7chp1qyj2dxds3pkg_59q5kr0000gp/T/munkipkg.9aYo8w3N/munki_app_component.plist
pkgbuild: Reading components from /var/folders/0z/7chp1qyj2dxds3pkg_59q5kr0000gp/T/munkipkg.9aYo8w3N/munki_app_component.plist
pkgbuild: Adding component at Applications/Managed Software Center.app
pkgbuild: Adding component at Applications/Managed Software Center.app/Contents/PlugIns/MSCDockTilePlugin.docktileplugin
pkgbuild: Adding component at Applications/Managed Software Center.app/Contents/Resources/MunkiStatus.app
pkgbuild: Adding top-level preinstall script
pkgbuild: Wrote package to /var/folders/0z/7chp1qyj2dxds3pkg_59q5kr0000gp/T/munkipkg.9aYo8w3N/munki_mpkg/munkitools_app-4.2.2759.pkg

Packaging munkitools_launchd-2.0.0.1969.pkg
pkgbuild: Inferring bundle components from contents of /var/folders/0z/7chp1qyj2dxds3pkg_59q5kr0000gp/T/munkipkg.9aYo8w3N/munki_launchd
pkgbuild: Writing new component property list to /var/folders/0z/7chp1qyj2dxds3pkg_59q5kr0000gp/T/munkipkg.9aYo8w3N/munki_launchd_component.plist
pkgbuild: Reading components from /var/folders/0z/7chp1qyj2dxds3pkg_59q5kr0000gp/T/munkipkg.9aYo8w3N/munki_launchd_component.plist
pkgbuild: Wrote package to /var/folders/0z/7chp1qyj2dxds3pkg_59q5kr0000gp/T/munkipkg.9aYo8w3N/munki_mpkg/munkitools_launchd-2.0.0.1969.pkg

productbuild: Wrote product to /path/to/munki_rebrand/munkitools-2.8.1.2835.pkg
Distribution package created at /path/to/munki_rebrand/munkitools-2.8.1.2835.pkg.

Removing temporary files...
Done.
```

**Comment by bochoven** [comment] 2016-08-26 10:23
It looks like munki_rebrand.py needs to convert all possible 'Managed Software Centre" locale strings to the desired one:

- InfoPlist.strings in all language folders
- MainMenu.strings needs to replace the correct localised name (e.g. 'Geführte Softwareaktualisierung' for German)

This will take some work to do right

**Comment by fuzzylogiq** [comment] 2016-08-26 14:12
OK, and which language are your clients set to? Finnish? Has it successfully patched fi.lproj in Managed Software Center in the git repo in the same folder as the script? Perhaps Sierra is getting its MainWindow string from somewhere else. Did you run munki_rebrand.py on Sierra?

**Comment by miikkali** [comment] 2016-08-26 15:12
Clients are set to English language by default.

I ran munki_rebrand.py on Sierra.

More later, as it's weekend (and my birthday, yay!)

## 

Miikkali

**Comment by miikkali** [comment] 2016-10-14 13:03
Hello! Still getting the same results. I checked through the files in `fi.lproj` and `en.lproj` and they were all successfully patched. Maybe after the weekend I'll fire up two VM's, one running macOS 10.11.6 and another running 10.12. Then I'll try to build and run a rebranded Munki in the same way on both. I'll report back. Meanwhile, do you at Oxford IT use this script currently successfully with Sierra? Am I the only one who sees this behaviour?

Addition: I am currently running macOS 10.12.1 Beta (16B2333a)

**Comment by fuzzylogiq** [comment] 2016-10-17 10:04
We currently neither install nor attempt to rebrand on Sierra, and as such this likely won't get fixed by us until we do and we can reproduce this. In the mean time, if you figure anything out, feel free to make a PR!

**Comment by miikkali** [comment] 2016-10-19 06:58
I think I figured it out. It's nothing to do with Sierra. It's about which default language I happened to have enabled on my Sierra machines (English English). The problem is that munki_rebrand.py replaces only one string, the appNameOriginal which by default is set to `Managed Software Center` but in en_GB, en_AU and en_CA the string is `Managed Software Centre` so munki_rebrand.py doesn't patch those at all. (Also it doesn't patch various other languages.) So munki_rebrand.py works fine on Sierra but localisation could be handled in a more complete fashion.

**Comment by bochoven** [comment] 2016-10-19 06:59
Check https://github.com/ox-it/munki-rebrand/blob/master/munki_rebrand.py#L51-L64

**Comment by fuzzylogiq** [comment] 2016-10-19 07:08
Yeah, this is exactly why we extended Arjen's original script, so that it would change the name for all localised versions of the name too. It's more likely that something in XCode or the OS itself has changed.

Let me try and test this in a VM later.

On Wed, Oct 19, 2016 at 7:58 AM +0100, "Miikkali Leppihalme" <notifications@github.com<mailto:notifications@github.com>> wrote:

I think I figured it out. It's nothing to do with Sierra. It's about which default language I happened to have enabled on my Sierra machines (English English). The problem is that munki_rebrand.py replaces only one string, the appNameOriginal which by default is set to Managed Software Center but in en_GB, en_AU and en_CA the string is Managed Software Centre so munki_rebrand.py doesn't patch those at all. (Also it doesn't patch various other languages.) So munki_rebrand.py works fine on Sierra but localisation could be handled in a more complete fashion.

**Comment by miikkali** [comment] 2016-10-19 08:04
I opened our production munkitools package with Pacifist. This pkg was built in May 2016 using `munki_rebrand.py`. It has the same problem with localisation, so this is not new after all. 

The reason I am seeing this now and not earlier, is that we have only recently started to manage and unify client configurations, and en_GB was chosen as the default OS language. 

So I would guess that if munki_rebrand.py does complete localizations in your environment, then I must have something wrong in mine. I am not adept at Python so I can't really say much on the script's workings. Which lines of the code should replace also other strings than $appNameOriginal? Where does it consider "Geführte Softwareaktualisierung" or "Центр Управления ПО"?

**Comment by bochoven** [comment] 2016-10-19 08:06
@miikkali Did you check https://github.com/ox-it/munki-rebrand/blob/master/munki_rebrand.py#L51-L64 ?

**Comment by miikkali** [comment] 2016-10-19 08:09
Ah, hmm, just a few minutes and I'll check. Now I think I might have understood something completely wrong in the beginning and made a stupid mistake.

**Comment by fuzzylogiq** [comment] 2016-10-19 08:13
I guess I can guess what you've done - you've edited all of those to be the new app name you wanted?

**Comment by miikkali** [comment] 2016-10-19 08:22
Yes. I hang my head in shame. I had understood the logic of the script upside-down. I thought it was searching through all the localizations listed in L51-64 and changing the name to whatever is specified right there, but it's the other way around: I need to specify there what strings the script should look for and then the script replaces it with $appNameWanted. 

It is a great day to feel dumb. I thank you for your time. I learned something new today. Apologies for raising a non-issue. Perhaps time to close this.

**Closed as completed** 2016-10-19 08:25 UTC

**Comment by fuzzylogiq** [comment] 2016-10-19 08:27
No worries. Glad you learned something! Maybe should make the bit that says you don't need to edit below this line a bit bolder :)
